# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: "windows-2022"
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Verify Dependencies
      run: go mod verify

    - name: Build
      run: go build -v -tags=integration ./...

    - name: Run go vet
      run: go vet -tags=integration ./...

    # TODO: Enable gofmt as this formatter has more diff than expected.
    # - name: Run go fmt
    #   shell: powershell
    #   run: |
    #     $diffCount = (gofmt -l .).Count
    #     if ( $diffCount -gt 0 ) {
    #       Write-Host "#==== Gofmt failed ====# $diffCount "
    #       Write-Host "#==== Files to format ====#"
    #       gofmt -l .
    #       Write-Host "#==== Required changes ====#"
    #       gofmt -d .
    #       exit 1
    #     }

    # TODO: Enable Golint after fixing export errors
    # - name: Install golint
    #   run: go install golang.org/x/lint/golint@latest

    # - name: Run golint
    #   run: golint ./...

    - name: Test
      run: go test -v -tags=integration ./...